name: CD
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
      
      - name: APT UPDATE and INSTALL SSHPASS
        run: sudo apt update && sudo apt install sshpass
          
      - name: deploy client
        run: |
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "
            cd Circul-art/ && 
            git pull origin develop && 
            cd client && 
            npm install && 
            npm run build
          "
      
      - name: deploy server
        run: |
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "
            cd Circul-art/ && 
            cd server && 
            npm install && 
            npm run build
          "

      - name: run migrations
        continue-on-error: true
        run: |
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "
            cd Circul-art/ &&
            cd server &&
            npm run migration:run || {
              echo '⚠️ Migration failed with error code $?';
              echo '⚠️ This might be normal if tables already exist. Continuing deployment...';
              exit 0;
            }
          "