name: CD

on:
  push:
    branches: [develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install root dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format:check

      - name: Run linting
        run: npm run lint

  deploy:
    needs: validate
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - name: Install sshpass
        run: sudo apt update && sudo apt install -y sshpass

      - name: Deploy Dockerized app on VPS
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "
            cd Circul-Art &&
            git pull origin develop &&
            docker compose down &&
            docker compose up --build -d
          "

      - name: Run migrations
        continue-on-error: true
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "
            cd Circul-Art &&
            docker compose exec backend npm run migration:run || {
              echo '⚠️ Migration failed (peut-être déjà appliquée). On continue...';
              exit 0;
            }
          "
